# Add your own tasks in files placed in lib/tasks ending in .rake,
# for example lib/tasks/capistrano.rake, and they will automatically be available to Rake.

require_relative "config/application"
require 'resque/tasks'

Rails.application.load_tasks

task 'resque:work' => :environment do
  CleanupJob.perform_now()
end